import type { FlowDefinition } from '../types/documents';

export const idealClientManifestoFlow: FlowDefinition = {
  id: 'ideal_client_manifesto',
  title: 'Manifiesto de Cliente Ideal',
  description:
    'Construye un perfil profundo, estrategico y accionable de tu cliente ideal.',
  estimatedMinutes: 18,
  steps: [
    {
      id: 'profile-base',
      title: 'Perfil base',
      description: 'Entendamos quien es esa persona en su contexto general.',
      fields: [
        {
          id: 'where_do_they_live',
          label: '1. Donde vive?',
          type: 'text',
          required: true,
          placeholder: 'Ej: Vive en ciudades principales de Colombia',
        },
        {
          id: 'how_they_describe_themselves',
          label: '2. Como se describen a si mismos y a su profesion?',
          type: 'textarea',
          required: true,
          placeholder: 'Ej: Se ven como emprendedores independientes, expertos, asesores...',
        },
        {
          id: 'time_in_profession',
          label: '3. Cuanto tiempo llevan en su profesion?',
          type: 'text',
          required: true,
          placeholder: 'Ej: Entre 2 y 5 anos',
        },
        {
          id: 'monthly_income',
          label: '4. Cuales son sus ingresos mensuales?',
          type: 'text',
          required: true,
          placeholder: 'Ej: Entre 3 y 8 millones al mes',
        },
        {
          id: 'who_is_ideal_client',
          label: '5. Quien es tu cliente ideal?',
          type: 'textarea',
          required: true,
          placeholder: 'Describe con claridad quien es esa persona.',
        },
      ],
    },
    {
      id: 'qualification',
      title: 'Calificacion del prospecto',
      description: 'Definamos quien califica, quien no y como decide.',
      fields: [
        {
          id: 'qualification_requirements',
          label: '6. Que debe tener, creer o ser alguien para calificar para tu oferta?',
          type: 'textarea',
          required: true,
        },
        {
          id: 'disqualifiers',
          label: '7. Que descalifica explicitamente a una persona como buen prospecto?',
          type: 'textarea',
          required: true,
        },
        {
          id: 'decision_making_style',
          label: '8. Como toman sus decisiones?',
          type: 'textarea',
          required: true,
        },
        {
          id: 'who_makes_decisions',
          label: '9. Quien las toma?',
          type: 'text',
          required: true,
          placeholder: 'Ej: Ellos mismos, su pareja, un socio, el equipo...',
        },
        {
          id: 'financial_management',
          label: '10. Como manejan sus finanzas?',
          type: 'textarea',
          required: true,
        },
        {
          id: 'what_they_spend_on',
          label: '11. En que gastan?',
          type: 'textarea',
          required: true,
        },
        {
          id: 'financial_situation',
          label: '12. Cual es su situacion financiera?',
          type: 'select',
          required: true,
          options: [
            { label: 'Estable', value: 'stable' },
            { label: 'Variable', value: 'variable' },
            { label: 'Inestable', value: 'unstable' },
            { label: 'En crecimiento', value: 'growing' },
          ],
        },
      ],
    },
    {
      id: 'language-and-identity',
      title: 'Lenguaje e identidad',
      description: 'Necesitamos entender como hablan y como viven su realidad.',
      fields: [
        {
          id: 'own_language',
          label: '13. Tienen su propio idioma?',
          type: 'textarea',
          required: true,
          placeholder: 'Describe si usan expresiones, terminos o codigos propios.',
        },
        {
          id: 'words_they_use',
          label: '14. Que palabras utilizan?',
          type: 'textarea',
          required: true,
        },
        {
          id: 'typical_day',
          label: '15. Como es su dia tipico?',
          type: 'textarea',
          required: true,
        },
      ],
    },
    {
      id: 'errors-and-stagnation',
      title: 'Errores y estancamiento',
      description: 'Aqui identificamos que los frena hoy.',
      fields: [
        {
          id: 'mistakes_they_make',
          label: '16. Que errores estan cometiendo?',
          type: 'textarea',
          required: true,
        },
        {
          id: 'stagnant_behaviors',
          label: '17. Que comportamientos los mantienen estancados?',
          type: 'textarea',
          required: true,
        },
        {
          id: 'current_attempts_to_solve',
          label: '18. Que estan intentando hacer para resolver sus problemas?',
          type: 'textarea',
          required: true,
        },
        {
          id: 'beliefs_about_problem_and_solution',
          label: '19. Que creen del problema y de la solucion?',
          type: 'textarea',
          required: true,
        },
      ],
    },
    {
      id: 'current-emotional-state',
      title: 'Situacion emocional actual',
      description: 'Vamos a profundizar en su tension interna y emocional.',
      fields: [
        {
          id: 'current_situation',
          label: '20. Cual es su situacion actual?',
          type: 'textarea',
          required: true,
        },
        {
          id: 'current_feeling',
          label: '21. Cual es su sentimiento actual?',
          type: 'textarea',
          required: true,
        },
        {
          id: 'fears',
          label: '22. A que le tienen miedo?',
          type: 'textarea',
          required: true,
        },
        {
          id: 'keeps_them_awake',
          label: '23. Que los mantiene despiertos por la noche?',
          type: 'textarea',
          required: true,
        },
        {
          id: 'who_are_they_angry_with',
          label: '24. Con quien estan enojados?',
          type: 'textarea',
          required: true,
        },
        {
          id: 'what_they_want_to_avoid',
          label: '25. Que quieren evitar o ahorrar?',
          type: 'textarea',
          required: true,
        },
      ],
    },
    {
      id: 'desired-outcome',
      title: 'Resultado deseado',
      description: 'Ahora definimos hacia donde quieren llegar.',
      fields: [
        {
          id: 'desired_feeling',
          label: '26. Cual es su sentimiento deseado?',
          type: 'textarea',
          required: true,
        },
        {
          id: 'desired_situation',
          label: '27. Cual es su situacion deseada?',
          type: 'textarea',
          required: true,
        },
        {
          id: 'obstacles_to_goals',
          label: '28. Que obstaculos tienen para lograr sus objetivos?',
          type: 'textarea',
          required: true,
        },
      ],
    },
    {
      id: 'consumption-and-context',
      title: 'Consumo y contexto cultural',
      description: 'Entendamos que consumen, donde aprenden y a quien escuchan.',
      fields: [
        {
          id: 'free_time_activities',
          label: '29. Que les gusta hacer en su tiempo libre?',
          type: 'textarea',
          required: true,
        },
        {
          id: 'what_they_read',
          label: '30. Que leen?',
          type: 'textarea',
          required: true,
        },
        {
          id: 'topics_of_interest',
          label: '31. Que temas les interesan?',
          type: 'textarea',
          required: true,
        },
        {
          id: 'who_they_follow',
          label: '32. A quienes siguen?',
          type: 'textarea',
          required: true,
        },
        {
          id: 'heroes_or_references',
          label: '33. Quienes son sus referentes o heroes?',
          type: 'textarea',
          required: true,
        },
        {
          id: 'where_they_get_information',
          label: '34. Donde se informan?',
          type: 'textarea',
          required: true,
        },
        {
          id: 'what_they_consume',
          label: '35. Que consumen?',
          type: 'textarea',
          required: true,
        },
        {
          id: 'where_they_belong',
          label: '36. Donde se congregan o se sienten parte de algo?',
          type: 'textarea',
          required: true,
        },
        {
          id: 'software_and_platforms',
          label: '37. Que software y plataformas utilizan?',
          type: 'textarea',
          required: true,
        },
      ],
    },
    {
      id: 'purchase-objections',
      title: 'Compra, objeciones y decision',
      description: 'Aqui cerramos con lo que influye en la compra.',
      fields: [
        {
          id: 'who_they_talk_to_before_buying',
          label: '38. Con quien hablan antes de tomar decisiones de compra?',
          type: 'textarea',
          required: true,
        },
        {
          id: 'what_they_research_before_buying',
          label: '39. Que investigan antes de comprar?',
          type: 'textarea',
          required: true,
        },
        {
          id: 'questions_they_have',
          label: '40. Que preguntas tienen?',
          type: 'textarea',
          required: true,
        },
        {
          id: 'solutions_they_hear_about',
          label: '41. Que soluciones escuchan?',
          type: 'textarea',
          required: true,
        },
        {
          id: 'what_they_think_about_available_solutions',
          label: '42. Que piensan de las soluciones disponibles?',
          type: 'textarea',
          required: true,
        },
        {
          id: 'what_they_wish_service_included',
          label: '43. Que les encantaria que incluyera el servicio?',
          type: 'textarea',
          required: true,
        },
        {
          id: 'objections_and_beliefs',
          label: '44. Que objeciones y creencias tienen?',
          type: 'textarea',
          required: true,
        },
        {
          id: 'what_convinces_them_to_buy',
          label: '45. Que los convence de comprar?',
          type: 'textarea',
          required: true,
        },
        {
          id: 'what_would_make_decision_easier',
          label: '46. Que hubiera hecho la decision mas facil?',
          type: 'textarea',
          required: true,
        },
        {
          id: 'why_they_see_you_different',
          label: '47. Por que te ven distinto?',
          type: 'textarea',
          required: true,
        },
      ],
    },
  ],
};